
# html lang
language: zh-Hans

# main menu navigation
menu:
  Home: /
  Tags: /tags
  Categories: /categories
  About: /about

# customize your terminal panel
terminal:
  #Home
  Blog:
    slogan: 
      typ: string
      val: No code no life. -- NekoDaemon
  #About
  NekoDaemon:
    education: 
      typ: string
      val: Southern University of bullShit and Trash
    interests:
      typ: string
      val: Embedded / Distributed / Heterogeneous System
    github:
      typ: link
      val: github.com/Tonny-Gu
      url: https://github.com/Tonny-Gu
  #Tags
  Tags:
  #Categories
  Categories:
  #Post
  Post:

#social media
#name: url
social:
  # github: https://github.com/lazysheep666
  # weibo: https://weibo.com/u/5318061001
  
# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
scripts:
- /js/nav.js
- /js/scroll.js
- /js/index.js
# the third-party loaded in the head
third_party:
  js:
    jquery: /js/third-party/jquery.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 
  css:
    font-awsome: https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css

